-keep,includedescriptorclasses public class com.google.firebase.database.DatabaseError{ *; }
-keep,includedescriptorclasses public class com.google.firebase.database.DatabaseReference{ *; }
-keep,includedescriptorclasses public class com.google.firebase.database.DataSnapshot{ *; }
-keep,includedescriptorclasses public class com.google.firebase.database.FirebaseDatabase{ *; }
-keep,includedescriptorclasses public class com.google.firebase.database.MutableData{ *; }
-keep,includedescriptorclasses public class com.google.firebase.database.OnDisconnect{ *; }
-keep,includedescriptorclasses public class com.google.firebase.database.Query{ *; }
